language: rust

rust:
  - stable
  - beta
  - nightly

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c79afdfc8c4cf025f58
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
