sudo: false
language: rust

env:
  global:
    - CRATE_NAME=cobalt

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env || true
  - which cargo-coveralls || cargo install cargo-travis
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (travis_wait cargo install rustfmt --force --vers 0.8.3) fi
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo install clippy --force || true) fi

script:
  - rustc -Vv
  - cargo -V
  - cargo check --verbose
  - cargo check --verbose --features "syntax-highlight"
  - cargo test  --verbose --features "syntax-highlight"
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (! which cargo-clippy || cargo clippy -- --version) fi
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (! which cargo-clippy || cargo clippy --features "syntax-highlight") fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo fmt -- --version) fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then (cargo fmt -- --write-mode=diff) fi

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "R4P4oXBODF9LZW/ht2putfF4tg74aOjWVRZWu7ia4ORdpEQ++RkgO32SQLZsLeXsJbb/qbTa06FfD6MC8MWdmek4DvwlSAiHrykVyio3BCv4RHmeBtaIhmp0L7n608tDeoJZFXE08JkDtR6rS8OiQw1jt6GuNAVGYk7/Rhgpujo="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

after_success:
  - if [ "$TRAVIS_RUST_VERSION" = "stable" -a "$TARGET" = "x86_64-unknown-linux-gnu" ]; then (cargo coverage) fi

addons:
  apt:
    packages:
      # necessary for `cargo coveralls`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

cache:
  apt: true
  directories:
    - $HOME/.cargo
    - target/debug/deps
    - target/debug/build
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e08f15b115326957c31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
