[package]

name = "cobalt-bin"
version = "0.3.0"
authors = ["Benny Klotz <r3qnbenni@gmail.com>", "Johann Hofmann <mail@johann-hofmann.com>"]
description = "Static site generator written in Rust"
repository = "https://github.com/cobalt-org/cobalt.rs"
readme = "README.md"
keywords = ["static", "site", "generator"]
license = "MIT"

[lib]
name="cobalt"

[[bin]]
name = "cobalt"
doc = false

[dependencies]
getopts = "0.2.14"
liquid = "0.8"
walkdir = "0.1"
crossbeam = "0.2"
yaml-rust = "0.3"
chrono = "0.2"
log = "0.3"
env_logger = "0.3"
rss = "0.3.1"
pulldown-cmark = "0.0.7"
hyper = "0.9"
notify = "^2.5.0"
ghp = "0.1"
glob = "0.2.11"
regex = "0.1"

[dev-dependencies]
difference = "0.4"

[features]
unstable = []
