[package]

name = "cobalt"
version = "0.1.2"
authors = ["Benny Klotz <r3qnbenni@gmail.com>", "Johann Hofmann"]

[dependencies]
getopts = "0.2.14"
markdown = "0.1"
liquid = "0.4"
walkdir = "0.1"
crossbeam = "0.1.5"
yaml-rust = "0.2.2"
chrono = "0.2"
log = "0.3"
env_logger = "0.3"

[dev-dependencies]
difference = "0.4"
