[package]
name = "cobalt-core"
version = "0.16.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Static site generator written in Rust"
repository = "https://github.com/cobalt-org/cobalt.rs"
readme = "../../README.md"
keywords = ["static", "site", "generator"]
categories = ["command-line-utilities"]
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
unstable = []
preview_unstable = []

[dependencies]
cobalt-config = { version = "=0.16.0", path = "..//config", features = ["unstable"] }
status = { version = "0.0.10", features = ["send_sync"] }
